### ISSUE TITLE
No longer works on HA 2022.0.9

### ISSUE THREAD

**Issue by larrignon** [AustinBrunkhorst/pysnooz#3]
I had the following problem after updating from HA 2022.8.7 (working great) to HA 2022.9.0.

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 7 septembre 2022 à 23:40:56 (3 occurrences)
Last logged: 7 septembre 2022 à 23:41:11

Unable to install package pysnooz==0.7.3: ERROR: Cannot install pysnooz==0.7.3 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Thanks for your great work.

**Comment by AustinBrunkhorst** [comment]
Thanks for reporting! [custom_components/snooz v0.1.3](https://github.com/AustinBrunkhorst/snooz/releases/tag/0.1.3) which uses [pysnooz v0.7.4](https://github.com/AustinBrunkhorst/pysnooz/releases/tag/v0.7.4) should fix this. Let me know if this is not the case for you.
